In [4]:
print("Hello World")

Hello World


In [5]:
import numpy as np


In [6]:
# numpy = numerical python
# pandas = dataframe/excel/csv/table
# matplotlib = visualization
# seaborn = visual
# sklearn = algorithms/data preprocessing
# scipy = statistical

In [7]:
simple_list=([6,7,9])
np.array(simple_list)

array([6, 7, 9])

In [8]:
arr=np.array([6,7,9])
arr


array([6, 7, 9])

In [9]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [11]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.arange(10,18)

array([10, 11, 12, 13, 14, 15, 16, 17])

In [13]:
np.arange(10,78,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74])

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.arange(6,dtype=int)

array([0, 1, 2, 3, 4, 5])

In [16]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [19]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [21]:
np.linspace(0,20,10)
# equal spacing

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [22]:
np.eye(5) 
# identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(2,4)

array([[0.06460684, 0.73793244, 0.0341661 , 0.11963153],
       [0.09386985, 0.03079758, 0.47742038, 0.49838496]])

In [24]:
np.random.randn(2,4)

array([[ 0.04992286,  0.34846157,  0.25815146,  0.18097539],
       [ 3.29116277, -0.78386457, -0.73401436,  1.50970857]])

In [25]:
np.random.rand(2,5)

array([[0.67647604, 0.82871375, 0.74245121, 0.91123191, 0.01239311],
       [0.50224748, 0.23405661, 0.66170186, 0.76720249, 0.3221826 ]])

In [26]:
np.random.randint(0,10,150)
# 150 numbers ranging from 0 to 9 

array([8, 0, 4, 0, 5, 8, 9, 2, 5, 4, 0, 5, 4, 7, 7, 7, 9, 4, 9, 9, 4, 3,
       7, 4, 7, 7, 3, 1, 8, 1, 9, 5, 9, 1, 5, 2, 4, 2, 9, 4, 5, 2, 2, 5,
       8, 5, 1, 2, 6, 1, 9, 7, 9, 4, 6, 1, 4, 5, 9, 9, 9, 4, 9, 6, 4, 0,
       8, 5, 1, 7, 4, 4, 4, 0, 4, 5, 4, 1, 3, 8, 8, 1, 1, 0, 5, 6, 2, 8,
       8, 9, 8, 1, 4, 5, 5, 0, 9, 6, 9, 2, 0, 1, 6, 6, 6, 8, 1, 2, 7, 7,
       8, 6, 8, 8, 5, 8, 8, 4, 9, 8, 4, 5, 9, 8, 7, 8, 6, 7, 7, 7, 7, 9,
       7, 9, 2, 1, 9, 2, 2, 5, 7, 1, 8, 9, 1, 5, 2, 4, 1, 5])

In [27]:
sample_array = np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
rand_array=np.random.randint(0,10,5)
rand_array

array([0, 5, 1, 2, 0])

In [30]:
sample_array.min()

2

In [31]:
sample_array.argmin()

0

In [32]:
rand_array.max()

5

In [33]:
rand_array.argmax()

1

In [34]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [35]:
sample_array=sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [36]:
sample_array[3]=100
sample_array

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [100, 100, 100],
       [ 22,  23,  24],
       [ 25,  26,  27]])

In [37]:
sample_array=np.arange(10,100)
sample_array


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [38]:
sample_array[0:5]


array([10, 11, 12, 13, 14])

In [39]:
subset_Sample_array=sample_array[0:7]
subset_Sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [40]:
sample_array[1:5]=1001
sample_array

array([  10, 1001, 1001, 1001, 1001,   15,   16,   17,   18,   19,   20,
         21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
         32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
         43,   44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
         54,   55,   56,   57,   58,   59,   60,   61,   62,   63,   64,
         65,   66,   67,   68,   69,   70,   71,   72,   73,   74,   75,
         76,   77,   78,   79,   80,   81,   82,   83,   84,   85,   86,
         87,   88,   89,   90,   91,   92,   93,   94,   95,   96,   97,
         98,   99])

In [41]:
sample_matrix=np.array([[24,13,2,15],[15,2,54,65],[56,76,24,7]])
sample_matrix


array([[24, 13,  2, 15],
       [15,  2, 54, 65],
       [56, 76, 24,  7]])

In [42]:
sample_matrix[2][2]

24

In [43]:
sample_matrix[:,3]

array([15, 65,  7])

In [44]:
sample_matrix[1:3,2:4]

array([[54, 65],
       [24,  7]])

In [45]:
sample_matrix[1:,2:]

array([[54, 65],
       [24,  7]])

In [46]:
sample_matrix[2]

array([56, 76, 24,  7])

In [47]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [48]:
sample_array+sample_array
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [49]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [50]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [51]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [52]:
np.max(sample_array)

30

In [53]:
np.min(sample_array)

1

In [54]:
np.argmin(sample_array)

0

In [55]:
np.argmax(sample_array)

29

In [56]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900])

In [57]:
np.std(sample_array)
# standard deviation

8.65544144839919

In [58]:
np.var(sample_array)
# variance

74.91666666666667

In [59]:
np.mean(sample_array)

15.5

In [60]:
array=np.random.randn(3,4)
# normal distribution
array

array([[-0.78712106, -1.05845073,  1.67193507, -0.65722465],
       [ 0.41101754, -1.4396174 ,  0.03214151, -0.89743904],
       [-0.21787695, -1.86083831,  1.13876482, -0.46845707]])

In [61]:
np.round(array,decimals=3)

array([[-0.787, -1.058,  1.672, -0.657],
       [ 0.411, -1.44 ,  0.032, -0.897],
       [-0.218, -1.861,  1.139, -0.468]])

In [62]:
fruits = np.array(['apple','orange','mango','apple','orange'])
np.unique(fruits)

array(['apple', 'mango', 'orange'], dtype='<U6')

In [63]:
import pandas as pd
import numpy as np

In [64]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [65]:
sports1['basketball']

3

In [66]:
sports2=pd.Series([11,13,12,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football    13
baseball    12
golf         4
dtype: int64

In [67]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football      15.0
golf           8.0
dtype: float64

In [68]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.739581  0.685894  0.520975  0.378407  0.458990
B  0.060581  0.938884  0.643908  0.958090  0.815549
C  0.204002  0.807651  0.707513  0.961618  0.193455
D  0.934186  0.366499  0.669400  0.575240  0.465805
E  0.170500  0.225380  0.949167  0.892737  0.047767
F  0.187400  0.078703  0.891830  0.837200  0.164587
G  0.767968  0.654207  0.720477  0.184013  0.511585
H  0.943368  0.796794  0.668983  0.469711  0.310202

In [69]:
df1[['Score2','Score3','Score4']]

Score2    Score3    Score4
A  0.685894  0.520975  0.378407
B  0.938884  0.643908  0.958090
C  0.807651  0.707513  0.961618
D  0.366499  0.669400  0.575240
E  0.225380  0.949167  0.892737
F  0.078703  0.891830  0.837200
G  0.654207  0.720477  0.184013
H  0.796794  0.668983  0.469711

In [70]:
df1['Score2']

A    0.685894
B    0.938884
C    0.807651
D    0.366499
E    0.225380
F    0.078703
G    0.654207
H    0.796794
Name: Score2, dtype: float64

In [71]:
df1['Score6']=df1['Score1']+df1['Score2']
df1['Score6']

A    1.425474
B    0.999465
C    1.011653
D    1.300685
E    0.395880
F    0.266103
G    1.422176
H    1.740162
Name: Score6, dtype: float64

In [72]:
df1.drop('E')

Score1    Score2    Score3    Score4    Score5    Score6
A  0.739581  0.685894  0.520975  0.378407  0.458990  1.425474
B  0.060581  0.938884  0.643908  0.958090  0.815549  0.999465
C  0.204002  0.807651  0.707513  0.961618  0.193455  1.011653
D  0.934186  0.366499  0.669400  0.575240  0.465805  1.300685
F  0.187400  0.078703  0.891830  0.837200  0.164587  0.266103
G  0.767968  0.654207  0.720477  0.184013  0.511585  1.422176
H  0.943368  0.796794  0.668983  0.469711  0.310202  1.740162

In [73]:
df1.drop('Score1',axis=1)

Score2    Score3    Score4    Score5    Score6
A  0.685894  0.520975  0.378407  0.458990  1.425474
B  0.938884  0.643908  0.958090  0.815549  0.999465
C  0.807651  0.707513  0.961618  0.193455  1.011653
D  0.366499  0.669400  0.575240  0.465805  1.300685
E  0.225380  0.949167  0.892737  0.047767  0.395880
F  0.078703  0.891830  0.837200  0.164587  0.266103
G  0.654207  0.720477  0.184013  0.511585  1.422176
H  0.796794  0.668983  0.469711  0.310202  1.740162

In [74]:
df1.drop("A",axis=0)

Score1    Score2    Score3    Score4    Score5    Score6
B  0.060581  0.938884  0.643908  0.958090  0.815549  0.999465
C  0.204002  0.807651  0.707513  0.961618  0.193455  1.011653
D  0.934186  0.366499  0.669400  0.575240  0.465805  1.300685
E  0.170500  0.225380  0.949167  0.892737  0.047767  0.395880
F  0.187400  0.078703  0.891830  0.837200  0.164587  0.266103
G  0.767968  0.654207  0.720477  0.184013  0.511585  1.422176
H  0.943368  0.796794  0.668983  0.469711  0.310202  1.740162

In [75]:
df1.drop(['Score1','Score2'],axis=1)

Score3    Score4    Score5    Score6
A  0.520975  0.378407  0.458990  1.425474
B  0.643908  0.958090  0.815549  0.999465
C  0.707513  0.961618  0.193455  1.011653
D  0.669400  0.575240  0.465805  1.300685
E  0.949167  0.892737  0.047767  0.395880
F  0.891830  0.837200  0.164587  0.266103
G  0.720477  0.184013  0.511585  1.422176
H  0.668983  0.469711  0.310202  1.740162

In [76]:
df2={'ID':[101,102,103,107,176],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [77]:
array2=np.array([5,4,64,3,3,3])
array2

array([ 5,  4, 64,  3,  3,  3])

In [81]:
arr=array2[4:6]
arr

array([3, 3])

In [79]:
arr

array([3, 3])

In [82]:
arr[0]=9
array2

array([ 5,  4, 64,  3,  9,  3])

In [85]:
array1=np.array([[3,2,6,7,7],[1,12,3,4,5]])
array1

array([[ 3,  2,  6,  7,  7],
       [ 1, 12,  3,  4,  5]])

In [86]:
array1[0,3]

7